version: "3.7"

services:

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/sites-available/:/etc/nginx/sites-available
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    command: ln -s /etc/nginx/sites-available/bbards.com /etc/nginx/sites-enabled/bbards.com && ln -s /etc/nginx/sites-available/api.bbards.com /etc/nginx/sites-enabled/api.bbards.com
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    links:
      - backend
      - frontend
    restart: always

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    restart: always
    environment:
      dbURI: ${dbURI}
      secret: ${secret}
      user: ${user}
      pass: ${pass}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}

    # env_file:
    #   - .env
    networks:
      - app-network
      - db
    depends_on:
      - mongo
    links:
      - mongo

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: ./.docker/Dockerfile
    restart: on-failure
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      - db
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  app-network:
    driver: bridge
  db:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  static-files:
