version: "3.7"

x-backend:
  &backend
  container_name: backend
  build:
    context: .
    dockerfile: ./.docker/Dockerfile
  restart: always
  command: npm run dev
  volumes:
    - ./src:/app/src
    - ./src/data:/app/data
  environment:
    - dbURI=mongodb://root:example@mongo:27017
  env_file:
    - .env
  networks:
    - app-network
  depends_on:
    - mongo
  links:
    - mongo

services:

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/sites-enabled/site-enabled.conf:/etc/nginx/sites-enabled:ro
      - ./.docker/sites-available/sites-available.conf:/etc/nginx/sites-available:ro
      - static-files:/usr/share/nginx/html
    depends_on:
      - backend1
      - backend2
      - backend3
      - frontend

  backend1:
    <<: *backend
    container_name: backend1
  backend2:
    <<: *backend
    container_name: backend2
  backend3:
    <<: *backend
    container_name: backend3

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: ./.docker/Dockerfile
    restart: on-failure
    networks:
      - app-network
    volumes:
      - ./client/src:/app/src
      - static-files:/app/build
    depends_on:
      - backend1
      - backend2
      - backend3

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    networks:
      - app-network
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  app-network:
    driver: bridge
  nginx-network:
    driver: bridge
  nginx_proxy_manager:
    name: npm_network

volumes:
  mongo-data:
    driver: local
  static-files:


